import Store from './model/Store'

const initialState = {
  current: 0,
  wallets: [
    {
      id: '1',
      name: 'Default',
      unit: '$',
      color: 'green',
      transactions: [
        {
          id: 1,
          type: 'income',
          money: 6000000,
          category: 'Tiền lương',
          time: new Date(),
          pinned: true,
          icon: '100',
        },
        {
          id: 2,
          type: 'expense',
          money: 20000,
          category: 'Ăn sáng',
          time: new Date(),
          pinned: false,
          icon: 'comet',
        },
        {
          id: 3,
          type: 'expense',
          money: 15000,
          category: 'Vá xe',
          time: new Date(),
          pinned: false,
          icon: 'bike',
        },
        {
          id: 4,
          type: 'income',
          money: 500000,
          category: 'Tiết kiệm',
          time: new Date(),
          pinned: false,
          icon: 'moneybag',
        },
      ],
    },
    {
      id: '2',
      name: 'Quỹ đen',
      unit: 'đ',
      color: 'orange',
      transactions: [
        {
          id: 1,
          type: 'income',
          money: 6000000,
          category: 'Tiền lương',
          time: new Date(),
          pinned: true,
          icon: '100',
        },
        {
          id: 2,
          type: 'expense',
          money: 20000,
          category: 'Ăn sáng',
          time: new Date(),
          pinned: false,
          icon: 'comet',
        },
        {
          id: 3,
          type: 'expense',
          money: 25000,
          category: 'Vá lốp',
          time: new Date(),
          pinned: false,
          icon: 'bike',
        },
        {
          id: 4,
          type: 'income',
          money: 500000,
          category: 'Tiết kiệm',
          time: new Date(),
          pinned: false,
          icon: 'moneybag',
        },
      ],
    },
    {
      id: '3',
      name: 'ATM',
      unit: '$',
      color: 'green',
      transactions: [
        {
          id: 1,
          type: 'income',
          icon: '100',
          money: 6000000,
          category: 'Tiền lương',
          time: new Date(),
          pinned: true,
        },
        {
          id: 2,
          type: 'expense',
          icon: 'comet',
          money: 20000,
          category: 'Ăn sáng',
          time: new Date(),
          pinned: false,
        },
        {
          id: 3,
          type: 'expense',
          icon: 'bike',
          money: 15000,
          category: 'Vá xe',
          time: new Date(),
          pinned: false,
        },
        {
          id: 4,
          type: 'income',
          icon: 'moneybag',
          money: 500000,
          category: 'Tiết kiệm',
          time: new Date(),
          pinned: false,
        },
      ],
    },
  ],
}

const store = Store.create(initialState)

export default store
